import { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Common/Header';
import Right from '../components/Checkout/right';
import Left from '../components/Checkout/left';
import Drawer from '../components/Common/Drawer/Drawer';
import BackDrop from '../components/Common/Drawer/BackDrop';

const Checkout = () => {
	const [drawer, setDrawer] = useState(false);
	const showDrawer = () => setDrawer(!drawer);

	let backdrop;

	if (drawer) {
		backdrop = <BackDrop showDrawer={showDrawer} />;
	}

	return (
		<div className=''>
			<Head>
				<title>Checkout</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header showDrawer={showDrawer} />
			<Drawer drawer={drawer} showDrawer={showDrawer} />
			{backdrop}

			<div className='lg:pt-[130px] lg:px-[20px] lg:pb-[60px] pt:pt-[60px] w-full flex relative lg:bg-[#f7f7f7] bg-white'>
				<div className='lg:w-[970px] flex lg:mx-[300px] w-full col counter'>
					<Right />
					<Left />
				</div>
			</div>
		</div>
	);
};

export default Checkout;
