import Head from 'next/head';
import Header from '../components/Common/Header';
import SideBar from '../components/Common/Sidebar';
import Orderdetail from '../components/order/Orderdetail';
import Order from '../components/order/Order';
import OrderM from '../components/order/OrderM';
import {useState} from 'react';
import BackDrop from '../components/Common/Drawer/BackDrop';
import Drawer from '../components/Common/Drawer/Drawer';

const order = () => {
	const [currentStep, setCurrentStep] = useState(1);

	const stepArray = ['Order Received', 'Order On The Way', 'Order Delivered'];

	const [drawer, setDrawer] = useState(false);
	const showDrawer = () => setDrawer(!drawer);

	let backdrop;

	if (drawer) {
		backdrop = <BackDrop showDrawer={showDrawer} />;
	}
	return (
		<div>
			<Head>
				<title>Order</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header showDrawer={showDrawer} />
			<Drawer drawer={drawer} showDrawer={showDrawer} />
			{backdrop}

			<div className='flex flex-wrap w-full h-auto min-h-screen bg-white SidebarBody '>
				<SideBar />
				<div className='lg:w-calc flex flex-start w-full px-[20px]'>
					<div className='hidden lg:flex'>
						<Orderdetail
							currentStep={currentStep}
							setCurrentStep={setCurrentStep}
							stepArray={stepArray}
						/>
						<Order
							currentStep={currentStep}
							setCurrentStep={setCurrentStep}
							stepArray={stepArray}
						/>
					</div>
					<OrderM
						currentStep={currentStep}
						setCurrentStep={setCurrentStep}
						stepArray={stepArray}
					/>
				</div>
			</div>
		</div>
	);
};

export default order;
