import { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Common/Header';
import SideBar from '../components/Common/Sidebar';
import ProfileForm from '../components/Profile/ProfileForm';
import Drawer from '../components/Common/Drawer/Drawer';
import BackDrop from '../components/Common/Drawer/BackDrop';
import Contact from '../components/contact/contact';
import Address from '../components/Address/Address';

const profile = () => {
	const [drawer, setDrawer] = useState(false);

	const showDrawer = () => setDrawer(!drawer);

	let backdrop;

	if (drawer) {
		backdrop = <BackDrop showDrawer={showDrawer} />;
	}
	return (
		<div>
			<Head>
				<title>Profile</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header showDrawer={showDrawer} />
			<Drawer drawer={drawer} showDrawer={showDrawer} />
			{backdrop}
			<div className='flex flex-wrap w-full h-auto min-h-screen bg-white SidebarBody top-t'>
				<SideBar />
				<div className='proContainer '>
					<div className='flex flex-col w-full'>
						<ProfileForm />
						<Contact />
						<Address />
					</div>
				</div>
			</div>
		</div>
	);
};

export default profile;
